resolver: lts-20.1

packages:
- ./chat-bots
- ./chat-bots-contrib
- ./cofree-bot

extra-deps:
- git: https://github.com/cofree-coffee/matrix-client-haskell.git
  commit: 0.1.4.2
  subdirs:
    - matrix-client


