# NOTE: This should be a good reference for github actions w.r.t haskell
# https://markkarpov.com/post/github-actions-for-haskell-ci.html

name: cabal:build
on:
  push:
    branches:
      - main
  pull_request:
    # types:
    #  - opened
    #  - synchronize

jobs:
  check-format:
    if: "!contains(github.event.pull_request.labels.*.name, 'ignore-server-format-checks')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: |
          ORMOLU_VERSION="0.7.2.0"
          ORMOLU_URL="https://github.com/tweag/ormolu/releases/download/${ORMOLU_VERSION}/ormolu-Linux.zip"
          echo "Downloading from ${ORMOLU_URL}"
          curl --fail --location --output ormolu.zip "${ORMOLU_URL}"
          unzip ormolu.zip
          ./ormolu --mode check $(git ls-files '*.hs')

  build-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cabal: ["3.10"]
        ghc: ["9.2.8", "9.4.8", "9.6.3", "9.8.2"]

    env:
      CONFIG: "--project-file=cabal.project"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Freeze
        run: |
          cabal configure --enable-tests --test-show-details=direct $CONFIG
          cabal freeze

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-name: cache-cabal
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-      

      - name: Build
        run: cabal build all $CONFIG

      - name: Test
        run: cabal test all $CONFIG

      - name: Haddock
        run: cabal haddock all $CONFIG

      - name: SDist
        run: cabal sdist all $CONFIG
